plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

changesetBaseRefs:
  - "main"
  - "origin/main"
  - "upstream/main"

npmRegistryServer: https://registry.npmjs.org

yarnPath: .yarn/releases/yarn-berry.cjs
